version: 2
jobs:
  build:
    working_directory: ~/todolist/client
    docker:
      - image: circleci/node:12-browsers
    steps:
      - checkout
      - restore_cache:
          key: v1-yarn-{{ checksum "yarn.lock" }}
      - run: yarn
      - save_cache:
          key: v1-yarn-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
            - ~/.cache/yarn
      - run: yarn lint:js
      - run: yarn lint:hbs
      - run:
          environment:
             NODE_OPTIONS: --max_old_space_size=4096
          command: COVERAGE=true yarn test
      - store_artifacts:
          path: coverage
